import {createApp} from 'vue';
import App from './App.vue';
import router from './router';
import Stat from './components/Stat.vue';
import Divider from './components/Divider.vue';
import Card from './components/Card.vue';
import Badge from './components/Badge.vue';
import Tabs from './components/Tabs.vue';
import DataBox from './components/DataBox.vue';
import MiniChart from './components/MiniChart.vue';
import BarBox from './components/BarBox.vue';
import Radar from './components/Radar.vue';
import '../style.css';
import '../figma-vue.css';
import '../typography.css';
import '../pipeline.css';
import '../delivery-analysis.css';
const app=createApp(App);
app.component('Stat',Stat);
app.component('Divider',Divider);
app.component('Card',Card);
app.component('Badge',Badge);
app.component('Tabs',Tabs);
app.component('DataBox',DataBox);
app.component('MiniChart',MiniChart);
app.component('BarBox',BarBox);
app.component('Radar',Radar);
app.use(router).mount('#app');
