<script setup>
import {useDashboard} from '../composables/useDashboard';
const {D,NAV,active,profileSub,deliverySub,role,alertOpen,apiError,supplierId,detailTab,priceTab,searchMode,search,ratingSearch,selectedMaterial,compareIds,profileYear,profileStatus,profileLevel,deliveryStart,deliveryEnd,deliveryStatus,deliveryOrderQuery,profileOverview,overviewRatingDistribution,ratingDonutStyle,fullRatingDonutStyle,selectedSupplierProfile,selectedPriceSummary,selectedPriceComparison,selectedCostFactors,riskAlerts,current,supplier,supplierList,overviewSuppliers,ratingList,dims,provinceOverview,filteredDeliveryOrders,deliveryStatusOptions,selectedFlowOrder,workflowNodes,deliverySummaryCards,abnormalOrders,fulfillmentRows,shortageRows,shortageSupplierChart,shortageMaterialChart,supplyExecution,supplierNameById,materialNameById,selectSupplier,toggleCompare}=useDashboard();
</script>
<template>
<section class="page-stack">
          <Tabs :items="['历史成交价查询','多供应商比价','成本因素分析']" v-model="priceTab"/>
          <div class="query-panel"><label>物料<select v-model="selectedMaterial"><option v-for="(m,i) in D.materials" :value="i">{{m[1]}}</option></select></label></div>
          <template v-if="priceTab===0"><div class="stat-grid four"><Stat label="最近成交价" :value="selectedPriceSummary?'¥'+selectedPriceSummary.latest.unit_price.toFixed(2):'暂无'" :sub="selectedPriceSummary?.latest.record_date||''"/><Stat label="最低价（当前样本）" :value="selectedPriceSummary?'¥'+selectedPriceSummary.minimum.toFixed(2):'暂无'" tone="green"/><Stat label="最高价（当前样本）" :value="selectedPriceSummary?'¥'+selectedPriceSummary.maximum.toFixed(2):'暂无'" tone="amber"/><Stat label="加权平均价" :value="selectedPriceSummary?'¥'+selectedPriceSummary.weightedAverage.toFixed(2):'暂无'" sub="按采购数量加权"/></div><Card :title="D.materials[selectedMaterial]?.[1]+' · 成交价格记录'" :sub="D.materials[selectedMaterial]?.[2]"><DataBox title="原始价格记录" :headers="['日期','供应商','成交价','采购数量']" :rows="(selectedPriceSummary?.records||[]).map(x=>[x.record_date,x.supplier_name,'¥'+x.unit_price.toFixed(2),x.purchase_qty])"/></Card><div class="grid two"><DataBox title="价格样本统计" :headers="['指标','结果','计算依据']" :rows="[['当前样本数',selectedPriceSummary?.records.length||0,'所选物料的价格记录'],['采购数量合计',(selectedPriceSummary?.records||[]).reduce((sum,x)=>sum+x.purchase_qty,0),'价格记录数量之和'],['供应商数',new Set((selectedPriceSummary?.records||[]).map(x=>x.supplier_id)).size,'所选物料的去重供应商']]"/><DataBox title="供应商成交价记录" :headers="['采购数量','单价']" :rows="(selectedPriceSummary?.records||[]).map(x=>[x.purchase_qty,'¥'+x.unit_price.toFixed(2)])"/></div></template>
          <template v-else-if="priceTab===1"><BarBox title="所选物料成交价对比" :values="selectedPriceComparison.map(x=>x[2])" :labels="selectedPriceComparison.map(x=>x[0].slice(0,5))"/><DataBox title="多供应商成交价明细" :headers="['供应商','物料','成交价','基准价','偏差','采购数量','质量合格率','时间遵守率']" :rows="selectedPriceComparison.map(x=>[x[0],x[1],'¥'+x[2].toFixed(2),'¥'+x[3].toFixed(2),x[4]+'%',x[5],x[6],x[7]])"/></template>
          <template v-else><DataBox title="所选物料成交价差估算" :headers="['供应商与物料','推算基准价','执行价差','偏差率','口径']" :rows="selectedCostFactors.map(x=>[x[0],'¥'+x[1].toFixed(2),(x[2]>0?'+':'')+'¥'+x[2].toFixed(2),x[3],x[4]])"/></template>
        </section>
</template>
